version: '3.9'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "4000:3000"

  fluentd:
    image: fluent/fluentd:v1.12-1
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - ./fluentd/log:/fluentd/log
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  promtail:
    image: grafana/promtail:2.7.1
    volumes:
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yaml
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yaml

  tempo:
    image: grafana/tempo:1.3.1
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo/tempo.yaml
    ports:
      - "3200:3200"
    command: -config.file=/etc/tempo/tempo.yaml

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
